# Лабораторная работа №1
## Выполнил студент группы БФИ1902 Агарков Максим Дмитриевич
### Задание №1 вывод сообщения


In [2]:
print("Hello, World!")

Hello, World!


### Задание №2 
#### Здесь создаётся массив, с которым в дальнейшем нам придётся работать, в дальнейшем.
##### У него есть такие параметры как количество строк и столбцов, а также минимальное и максимальное значение.

In [3]:
from random import randint
import numpy as np

n, m = 10, 10
min_limit = -250
max_limit = 250


a = [[randint(min_limit, max_limit) for j in range(m)] for i in range(n)]
an = np.asarray(a)
print(an)

[[-131  206  100  140  -16 -220  186  -77   35   86]
 [ -26 -201  -30 -225  -54 -201  214 -112   -7  169]
 [  86  165  -55   95   27  -92 -183  225  178 -202]
 [ -55   19  -70  159 -131 -116   -1   14 -227 -214]
 [ 248 -158 -248 -135 -100   43 -124  -26   30 -136]
 [ -73 -222 -184  191 -241   54 -169  235   17   27]
 [-203   78  167  233   96 -149 -137  204 -175  132]
 [ 192   79  126 -153   66   83  -30 -238  197  246]
 [  82  210   -8   25   31 -235 -172   88   58  -92]
 [ 140   13  235  -38 -113 -121  -86 -152 -164 -182]]


### Задание №3

### Сортировка выбором 
#### Берём первый элемент сравниваем со вторым, ищем наименьший. 


In [4]:
%%time
import numpy as np

def selection_sort(nums):  
    for i in range(len(nums)):
        lowest_value_index = i
        for j in range(i + 1, len(nums)):
            if nums[j] < nums[lowest_value_index]:
                lowest_value_index = j
        nums[i], nums[lowest_value_index] = nums[lowest_value_index], nums[i]

k=0
while k<=n-1:
    selection_sort(a[k])
    k=k+1

an = np.asarray(a)
print(an) 

[[-220 -131  -77  -16   35   86  100  140  186  206]
 [-225 -201 -201 -112  -54  -30  -26   -7  169  214]
 [-202 -183  -92  -55   27   86   95  165  178  225]
 [-227 -214 -131 -116  -70  -55   -1   14   19  159]
 [-248 -158 -136 -135 -124 -100  -26   30   43  248]
 [-241 -222 -184 -169  -73   17   27   54  191  235]
 [-203 -175 -149 -137   78   96  132  167  204  233]
 [-238 -153  -30   66   79   83  126  192  197  246]
 [-235 -172  -92   -8   25   31   58   82   88  210]
 [-182 -164 -152 -121 -113  -86  -38   13  140  235]]
CPU times: user 902 µs, sys: 0 ns, total: 902 µs
Wall time: 828 µs


### Сортировка вставками 
####  каждый элемент со всеми сравнивается и будет в цикле увеличиваться область сравнения на один за итерацию.


In [5]:
%%time
import numpy as np

def insertion_sort(nums):  
    for i in range(1, len(nums)):
        item_to_insert = nums[i]
        j = i - 1
        while j >= 0 and nums[j] > item_to_insert:
            nums[j + 1] = nums[j]
            j -= 1
        nums[j + 1] = item_to_insert

k=0
while k<=n-1:
    insertion_sort(a[k])
    k=k+1

an = np.asarray(a)
print(an) 

[[-220 -131  -77  -16   35   86  100  140  186  206]
 [-225 -201 -201 -112  -54  -30  -26   -7  169  214]
 [-202 -183  -92  -55   27   86   95  165  178  225]
 [-227 -214 -131 -116  -70  -55   -1   14   19  159]
 [-248 -158 -136 -135 -124 -100  -26   30   43  248]
 [-241 -222 -184 -169  -73   17   27   54  191  235]
 [-203 -175 -149 -137   78   96  132  167  204  233]
 [-238 -153  -30   66   79   83  126  192  197  246]
 [-235 -172  -92   -8   25   31   58   82   88  210]
 [-182 -164 -152 -121 -113  -86  -38   13  140  235]]
CPU times: user 563 µs, sys: 0 ns, total: 563 µs
Wall time: 490 µs


### Пирамидальная сортировка
#### Принцип заключается в построении пирамидального дерева. Бинарное дерево это где от каждого узла выходит две ветви. Сравнивается узел с его ветвями снизу вверх, так чтобы на пирамиде самый большой элемент попал наверх. Потом, меняется элемент “на вершине”, то есть с индексом = 0, на последний элемент, после чего последний элемент пломбируется, ставится ограничение, что дальше будет рассматриваться i-1 элементов.


In [6]:
%%time
import numpy as np

def heap_sort(alist):
    build_max_heap(alist)
    for i in range(len(alist) - 1, 0, -1):
        alist[0], alist[i] = alist[i], alist[0]
        max_heapify(alist, index=0, size=i)
 
def parent(i):
    return (i - 1)//2
 
def left(i):
    return 2*i + 1
 
def right(i):
    return 2*i + 2
 
def build_max_heap(alist): 
    length = len(alist)
    start = parent(length - 1)
    while start >= 0:
        max_heapify(alist, index=start, size=length)
        start = start - 1
 
def max_heapify(alist, index, size):
    l = left(index)
    r = right(index)
    if (l < size and alist[l] > alist[index]):
        largest = l
    else:
        largest = index
    if (r < size and alist[r] > alist[largest]):
        largest = r
    if (largest != index):
        alist[largest], alist[index] = alist[index], alist[largest]
        max_heapify(alist, largest, size)

k=0
while k<=n-1:
    heap_sort(a[k])
    k=k+1

an = np.asarray(a)
print(an) 

[[-220 -131  -77  -16   35   86  100  140  186  206]
 [-225 -201 -201 -112  -54  -30  -26   -7  169  214]
 [-202 -183  -92  -55   27   86   95  165  178  225]
 [-227 -214 -131 -116  -70  -55   -1   14   19  159]
 [-248 -158 -136 -135 -124 -100  -26   30   43  248]
 [-241 -222 -184 -169  -73   17   27   54  191  235]
 [-203 -175 -149 -137   78   96  132  167  204  233]
 [-238 -153  -30   66   79   83  126  192  197  246]
 [-235 -172  -92   -8   25   31   58   82   88  210]
 [-182 -164 -152 -121 -113  -86  -38   13  140  235]]
CPU times: user 793 µs, sys: 19 µs, total: 812 µs
Wall time: 710 µs


### Быстрая сортировка
#### Выбирается опорный элемент в массиве, всё что больше этого элемента помещается вправо, всё что меньше - влево. Далее рекурсивно повторяется для левой и правой части, там соответственно выбирается опорный элемент и так до тех пор пока нечего будет делить.


In [7]:
%%time
import numpy as np

def quick_sort(data):
    less = []
    pivotList = []
    more = []
    if len(data) <= 1:
        return data
    else:
        pivot = data[0]
        for i in data:
            if i < pivot:
                less.append(i)
            elif i > pivot:
                more.append(i)
            else:
                pivotList.append(i)
        less = quick_sort(less)
        more = quick_sort(more)
        return less + pivotList + more

k=0
while k<=n-1:
    quick_sort(a[k])
    k=k+1

an = np.asarray(a)
print(an) 

[[-220 -131  -77  -16   35   86  100  140  186  206]
 [-225 -201 -201 -112  -54  -30  -26   -7  169  214]
 [-202 -183  -92  -55   27   86   95  165  178  225]
 [-227 -214 -131 -116  -70  -55   -1   14   19  159]
 [-248 -158 -136 -135 -124 -100  -26   30   43  248]
 [-241 -222 -184 -169  -73   17   27   54  191  235]
 [-203 -175 -149 -137   78   96  132  167  204  233]
 [-238 -153  -30   66   79   83  126  192  197  246]
 [-235 -172  -92   -8   25   31   58   82   88  210]
 [-182 -164 -152 -121 -113  -86  -38   13  140  235]]
CPU times: user 1.43 ms, sys: 0 ns, total: 1.43 ms
Wall time: 1.2 ms


### Сортировка обменом 
#### Её смысл заключается в том, что мы элемент сравниваем последовательно друг с другом и меняем местами, если предшествующий элемент больше последующего.


In [8]:
%%time
import numpy as np

def bubble_sort(nums):  
    swapped = True
    while swapped:
        swapped = False
        for i in range(len(nums) - 1):
            if nums[i] > nums[i + 1]:
                # Заменить элементы
                nums[i], nums[i + 1] = nums[i + 1], nums[i]
                swapped = True

k=0
while k<=n-1:
    bubble_sort(a[k])
    k=k+1

an = np.asarray(a)
print(an) 

[[-220 -131  -77  -16   35   86  100  140  186  206]
 [-225 -201 -201 -112  -54  -30  -26   -7  169  214]
 [-202 -183  -92  -55   27   86   95  165  178  225]
 [-227 -214 -131 -116  -70  -55   -1   14   19  159]
 [-248 -158 -136 -135 -124 -100  -26   30   43  248]
 [-241 -222 -184 -169  -73   17   27   54  191  235]
 [-203 -175 -149 -137   78   96  132  167  204  233]
 [-238 -153  -30   66   79   83  126  192  197  246]
 [-235 -172  -92   -8   25   31   58   82   88  210]
 [-182 -164 -152 -121 -113  -86  -38   13  140  235]]
CPU times: user 1.1 ms, sys: 36 µs, total: 1.14 ms
Wall time: 963 µs


### Сортировка Шелла
#### За один шаг сравниваются элементы которые находятся на расстоянии этого шага. Который рассчитывается по d= n/2 n - длина массива. Следующий шаг уменьшается вдвое и так далее.


In [9]:
%%time
import numpy as np

def shell_sort(nums):
    inc = len(nums) // 2
    while inc:
        for i, el in enumerate(nums):
            while i >= inc and nums[i - inc] > el:
                nums[i] = nums[i - inc]
                i -= inc
            nums[i] = el
        inc = int(inc // 2)
    return nums

k=0
while k<=n-1:
    shell_sort(a[k])
    k=k+1

an = np.asarray(a)
print(an) 

[[-220 -131  -77  -16   35   86  100  140  186  206]
 [-225 -201 -201 -112  -54  -30  -26   -7  169  214]
 [-202 -183  -92  -55   27   86   95  165  178  225]
 [-227 -214 -131 -116  -70  -55   -1   14   19  159]
 [-248 -158 -136 -135 -124 -100  -26   30   43  248]
 [-241 -222 -184 -169  -73   17   27   54  191  235]
 [-203 -175 -149 -137   78   96  132  167  204  233]
 [-238 -153  -30   66   79   83  126  192  197  246]
 [-235 -172  -92   -8   25   31   58   82   88  210]
 [-182 -164 -152 -121 -113  -86  -38   13  140  235]]
CPU times: user 765 µs, sys: 0 ns, total: 765 µs
Wall time: 719 µs


### Турнирная сортировка
#### Берём и строим двоичное дерево или сортируем набор последовательный или непоследовательных значений. Разбиваем последовательность на двойки и ищем минимальное, затем из этих минимальных также разбиваем и ищем минимальные, пока не найдём самое минимальное, берём его и выписываем в начало. А потом мы заменяем его на бесконечность (на какое-то огромное число), также если какому-то числу не хватило пары, то мы ему в пару ставим огромное число, чтобы изначальное прошло на этап дальше. Устраиваются переигровки, с сопутствующей заменой чисел на бесконечность. Когда видно, что не остаётся элементов которые мы не удалили, то алгоритм останавливается.

In [10]:
%%time
import numpy as np

def tournamentSort(arr):
    tree = [None] * 2 * (len(arr) + len(arr) % 2)
    index = len(tree) - len(arr) - len(arr) % 2

    for i, v in enumerate(arr):
        tree[index + i] = (i, v)

    for j in range(len(arr)):
        n = len(arr)
        index = len(tree) - len(arr) - len(arr) % 2
        while index > -1:
            n = (n + 1) // 2
            for i in range(n):
                i = max(index + i * 2, 1)
                if tree[i] is not None and tree[i + 1] is not None:
                    if tree[i] < tree[i + 1]:
                        tree[i // 2] = tree[i]
                    else:
                        tree[i // 2] = tree[i + 1]
                else:
                        tree[i // 2] = tree[i] if tree[i] is not None else tree[i + 1]
            index -= n
    
        index, x = tree[0]
        arr[j] = x
        tree[len(tree) - len(arr) - len(arr) % 2 + index] = None

k=0
while k<=n-1:
    tournamentSort(a[k])
    k=k+1

an = np.asarray(a)
print(an) 

[[-220 -131  -77  -16   35   86  100  140  186  206]
 [-225 -201 -201 -112  -54  -30  -26   -7  169  214]
 [-202 -183  -92  -55   27   86   95  165  178  225]
 [-227 -214 -131 -116  -70  -55   -1   14   19  159]
 [-248 -158 -136 -135 -124 -100  -26   30   43  248]
 [-241 -222 -184 -169  -73   17   27   54  191  235]
 [-203 -175 -149 -137   78   96  132  167  204  233]
 [-238 -153  -30   66   79   83  126  192  197  246]
 [-235 -172  -92   -8   25   31   58   82   88  210]
 [-182 -164 -152 -121 -113  -86  -38   13  140  235]]
CPU times: user 2.09 ms, sys: 0 ns, total: 2.09 ms
Wall time: 2 ms


# Вывод
## В данной лабораторной работе были изучаны разные методы сортировок в массивах. Также было просмотренно как разные алгоритмы справляются с одиннаковыми задачами и сравнено по времени. С поставленной задачей лучше всего справилась сортировка вставками.